language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - GOAL=verify
  - if [ "${TRAVIS_BRANCH}" = "release" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then GOAL="release:prepare release:perform"; git checkout release; fi;

script:
  - mvn -B -Dusername=$GH_TOKEN clean $GOAL

after_success:
  - mvn clean

after_failure:
  - mvn -V

after_script:
  - mvn compile