language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
before_script:
- git checkout -b temporary
- GOAL=verify
- if [ "${TRAVIS_BRANCH}" = "release" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then GOAL="release:prepare release:perform"; fi;
script:
- mvn -B -Dusername=$GH_TOKEN clean $GOAL