language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  - GOAL=verify
  - GOAL=package
services:
  - mysql

cache:
  directories:
  - $HOME/.m2

before_script:
  - if [ "${TRAVIS_BRANCH}" = "release" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then GOAL="release:prepare release:perform"; git checkout release; fi;
  - mysql -e "create database mallow"
script:
  - mvn -B -Dusername=$GH_TOKEN -Darquillian.launch=glassfish-embedded-mysql $GOAL
